name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm install
    - name: Setup Pages
      id: pages
      uses: actions/configure-pages@v5
    - name: Build for web
      run: npx expo export --platform web
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v3
      with:
        branch: gh-pages
        folder: ./dist
        token: ${{ secrets.GITHUB_TOKEN }}